### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by tomihad-ul-aibak** [Lucidium123/YanZsource#1]
Its showing an error of unexpected token

**Comment by tomihad-ul-aibak** [comment]
@Lucidium123

**Comment by Nishant1500** [comment]
Can You Show The Full Error Code?

**Comment by tomihad-ul-aibak** [comment]
> Can You Show The Full Error Code?

Ogey

**Comment by Nishant1500** [comment]
> Nish: Can You Show The Full Error Code?
> 
> Oofy45isnoob: Ogey

  Show?

**Comment by tomihad-ul-aibak** [comment]
its showing different error 

internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/runner/YanZsource-1/node_modules/canvas/build/Release/canvas.node: invalid ELF header
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/runner/YanZsource-1/node_modules/canvas/lib/bindings.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)

**Comment by Nishant1500** [comment]
> ```shell
> internal/modules/cjs/loader.js:1122
> return process.dlopen(module, path.toNamespacedPath(filename));
> ^
>
> Error: /home/runner/YanZsource-1/node_modules/canvas/build/Release/canvas.node: invalid ELF header
> at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
> at Module.load (internal/modules/cjs/loader.js:928:32)
> at Function.Module._load (internal/modules/cjs/loader.js:769:14)
> at Module.require (internal/modules/cjs/loader.js:952:19)
> at require (internal/modules/cjs/helpers.js:88:18)
> at Object. (/home/runner/YanZsource-1/node_modules/canvas/lib/bindings.js:3:18)
> at Module._compile (internal/modules/cjs/loader.js:1063:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
> at Module.load (internal/modules/cjs/loader.js:928:32)
> at Function.Module._load (internal/modules/cjs/loader.js:769:144

Hello Again!
```shell
> process.dlopen;
             ^
  Error In Process Is Happening Because It Lacks Administration Permissions.
```
It Should Probably Fix The Issue By Just Simply Using A Administrator Command Prompt.

**Don't Know How To Open A Administrator Command Prompt?**
Don't worry, you can always ask about that

If This Solved Your Problem, Please Close This Issue :)

**Comment by tomihad-ul-aibak** [comment]
hwo to do it

**Comment by Nishant1500** [comment]
# Windows
These Methods Ar For Microsoft Windows Platform
### Win 10/8
In **Windows 10** and **Windows 8**, follow these steps:

Press `Windows Key` + `X` Select Command Prompt (Admin) to open an elevated command prompt.

### Win 7
In **Windows 7**, follow these steps:

Type cmd in Start search.

In the results, you will see ‘cmd‘.
Right Click On "Command Prompt" and Select "Run As Administrator"
# Linux And Mac OS
Open Normal Command Prompt

You Can Do `sudo <command>` To Use Commands As Administrator
For example- `sudo node index.js`

`sudo` can be both done on Mac OS And Linux

Hope This Helps You :)
If This Does Then Please Close This Issue 😃

Cheers,
Nish

**Comment by tomihad-ul-aibak** [comment]
but am running on repl.it

**Comment by Nishant1500** [comment]
Welp Then Ask Repl.It to give you administator perms :>
If I Rememeber Correctly, Repl.it doesnt give admin perms to anyone

**Comment by tomihad-ul-aibak** [comment]
Omg

**Comment by Nishant1500** [comment]
??

**Comment by tomihad-ul-aibak** [comment]
Im so dumb

**Comment by Nishant1500** [comment]
You Should Probably Close This Issue :)
